imports:
    - php

tools:
    external_code_coverage:
        timeout: 600

    php_code_sniffer:       true

    php_cpd:                true

    php_cs_fixer:           true

    php_mess_detector:      true

    php_pdepend:            true

    php_loc:                true

    php_analyzer:
        config:
            doc_comment_fixes:
                enabled:    true

    sensiolabs_security_checker: true

changetracking:
    bug_patterns: ["\bfix(?:es|ed)?\b"]
    feature_patterns: ["\badd(?:s|ed)?\b", "\bimplement(?:s|ed)?\b"]
