imports:
    - php

tools:
    external_code_coverage: true
    # PHP
    php_code_sniffer:       true
    php_cpd:                true
    php_cs_fixer:           true
    php_hhvm:               true
    php_mess_detector:      true
        config:
            code_size_rules:
                too_many_methods:     false

    php_pdepend:            true
    php_loc:                true
    php_analyzer:
        config:
            doc_comment_fixes:
                enabled:    true

changetracking:
    bug_patterns: ["\bfix(?:es|ed)?\b"]
    feature_patterns: ["\badd(?:s|ed)?\b", "\bimplement(?:s|ed)?\b"]
