language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: 5.6

install:
    - composer install --prefer-source

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
